crashkonijn/GOAP

Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapSetJobRunner.cs
Package/Runtime/CrashKonijn.Goap/Extensions.cs
Package/Runtime/CrashKonijn.Goap/Extensions.cs.meta

Fixed bug with Runner crashing after destroying an agent.

Added agent null check to GoapSetJobRunner

---

Package/Runtime/CrashKonijn.Goap.Resolver/GraphResolver.cs
Package/Runtime/CrashKonijn.Goap.Resolver/GraphResolverJob.cs
Package/Runtime/CrashKonijn.Goap.Resolver/ResolveHandle.cs
Package/Runtime/CrashKonijn.Goap.Resolver/com.crashkonijn.goap.resolver.asmdef

Fixed Collections >= 2.1 breaking package

---

Package/Runtime/CrashKonijn.Goap/Classes/GoapSet.cs
Package/Runtime/CrashKonijn.Goap/Interfaces/IGoapSet.cs

Created a readonly public getter for retrieving the list of goals from GoapSet as discussed with @SiliconOrchid yesterday.
Passes Unity tests runner.

Created a readonly public getter for retrieving the list of goals 

---

Package/Documentation/Classes/README.md
Package/Documentation/Config/README.md

Relates (at least partially) to https://github.com/crashkonijn/GOAP/issues/37

Removed empty readme files that were generating warnings/errors

---

Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/NodeViewerEditorWindow.cs

Fix: NodeViewer breaking

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

Added issue templates

---

.github/workflows/main.yml

With these changes it should be possible to run PR's from forks.

Changed workflow to allow forks to run, after approval

---

Package/Documentation/Classes/AgentBehaviour.md

Edit by CrashKonijn: This is a test with a colleague to check the pipeline.

Improved docs AgentBehaviour.md

---

Package/Documentation/Classes/Actions.md
Package/Documentation/Classes/AgentBehaviour.md
Package/Runtime/CrashKonijn.Goap/Behaviours/ActionBase.cs
Package/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs
Package/Runtime/CrashKonijn.Goap/Interfaces/IActionBase.cs
Package/Runtime/CrashKonijn.Goap/Interfaces/IAgent.cs
Package/Runtime/CrashKonijn.Goap/Interfaces/IAgentDistanceObserver.cs
Package/Runtime/CrashKonijn.Goap/Interfaces/IAgentDistanceObserver.cs.meta
Package/Runtime/CrashKonijn.Goap/Observers/VectorDistanceObserver.cs
Package/Runtime/CrashKonijn.Goap/Observers/VectorDistanceObserver.cs.meta
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentBehaviourTests.cs

- Feature: Added ability to customize the distance check. This allows you to use `NavMeshAgent.remainingDistance` for example.
- Feature: It is now possible to override the `IsInRange` method on an action. This allows you to perform line of sight checks for example.
Fixes: #44

Feature: custom distance and range check

---

Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapSetJobRunner.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/GoapSetJobRunnerTests.cs

Allow to re-queue action

---

.github/workflows/pull-request-labeler.yml
.github/workflows/release-drafter.yml

Added a release drafter workflow, this will now auto-label PR's and draft a release from the changes on master.
This will work towards fixing #93

chore: Added release-drafter

---

Package/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs
Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapSetJobRunner.cs
Package/Runtime/CrashKonijn.Goap/Interfaces/IAgent.cs

Fix: Goal completion not clearing goal

---

Package/Documentation/Introduction/GettingStarted.md

Missing using UnityEngine, that is needed for Vector3 and Random

docs: Update GettingStarted.md with missing using 

---

Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Actions/EatAppleAction.cs
Package/Editor/CrashKonijn.Goap.Editor/Drawers/ObjectDrawer.cs
Package/Editor/CrashKonijn.Goap.Editor/Elements/ListElementBase.cs
Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/NodeDrawer.cs
Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/NodesDrawer.cs
Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/WorldDataDrawer.cs
Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/AgentEditor.cs
Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgent.cs
Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgentType.cs
Package/Runtime/CrashKonijn.Goap.Core/Interfaces/ILocalWorldData.cs
Package/Runtime/CrashKonijn.Goap.Core/Interfaces/ISensorRunner.cs
Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IWorldData.cs
Package/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs
Package/Runtime/CrashKonijn.Goap/Classes/AgentType.cs
Package/Runtime/CrashKonijn.Goap/Classes/AgentTypeFactory.cs
Package/Runtime/CrashKonijn.Goap/Classes/Runners/AgentTypeJobRunner.cs
Package/Runtime/CrashKonijn.Goap/Classes/Runners/SensorRunner.cs
Package/Runtime/CrashKonijn.Goap/GlobalWorldData.cs
Package/Runtime/CrashKonijn.Goap/LocalWorldData.cs
Package/Runtime/CrashKonijn.Goap/WorldDataBase.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentBehaviourTests.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentTypeJobRunnerTests.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/SensorRunnerTests.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/WorldDataBaseTests.cs

Improvement:
- Instead of data being copied from global > local every time the global data is stored as a parent in local data. When the local data doesn't contain something the local world data will look at the global data.

Feature: Improved handling of world data

---

Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/NodeDrawer.cs
Package/Editor/CrashKonijn.Goap.Editor/Styles/Generic.uss
Package/Editor/CrashKonijn.Goap.Editor/Styles/NodeViewer.uss
Package/Editor/CrashKonijn.Goap.Editor/Styles/NodeViewer_2022.uss

Fixes issues that @CuteRogue fixed on a fork: https://github.com/TwinFaerie/GOAP/commit/962ec83eb8a247bba7a824396d776b83ccb3ae06

Feature: Improved editor readability (especially in light mode)

---

Package/Documentation/Introduction/GettingStarted.md
README.md

Added video tutorial references!

Docs: Added tutorial references

---

Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/NodeViewerEditorWindow.cs

Fix: Impossible to scroll agent list in node viewer

---

Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/NodeViewerEditorWindow.cs

Special thanks to @SauronDark for mentioning this!

Fixed node viewer breaking in 2021

---

Package/Editor/CrashKonijn.Goap.Editor/GoapEditorSettings.cs
Package/Editor/CrashKonijn.Goap.Editor/Styles/NodeViewer_2022.uss

Fix: Editor breaking when package is moved around

---

Package/Editor/CrashKonijn.Goap.Editor/Drawers/ObjectDrawer.cs
Package/Editor/CrashKonijn.Goap.Editor/Extensions.cs
Package/Editor/CrashKonijn.Goap.Editor/Extensions.cs.meta
Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/AgentEditor.cs

Fixed AgentEditor performance issue

---

Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/ClassFinder.cs
Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/ClassFinder.cs.meta
Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/AgentDrawer.cs
Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/NodeViewerEditorWindow.cs

Solution kindly provided by @Naokim
Fixes #146

Fixes #146, editor referencing concrete classes

---

Package/Runtime/CrashKonijn.Goap/Classes/Controllers/ProactiveController.cs
Package/Runtime/CrashKonijn.Goap/Classes/Controllers/ReactiveController.cs

Requeue agent when no action is found

---

Package/Editor/CrashKonijn.Goap.Editor/Drawers/ObjectDrawer.cs

Fixes null ref in ObjectDrawer

---

Package/Runtime/CrashKonijn.Goap/Behaviours/GoapRunnerBehaviour.cs
Package/Runtime/CrashKonijn.Goap/Behaviours/GoapSetBehaviour.cs
Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapRunner.cs
Package/Runtime/CrashKonijn.Goap/Interfaces/IGoapRunner.cs

Fixes scriptable config not using the correct goap config.

Fixes #177

---

Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/AgentTypeBehaviour.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Runners/SensorRunner.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Validators/AgentTypeConfigValidatorRunner.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Validators/DuplicateTargetSensorValidator.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Validators/DuplicateTargetSensorValidator.cs.meta
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Validators/DuplicateWorldSensorValidator.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Validators/DuplicateWorldSensorValidator.cs.meta
Package/Runtime/CrashKonijn.Goap.Runtime/Scriptables/AgentTypeScriptable.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Scriptables/CapabilityConfigScriptable.cs

Fix: sensor bricking from duplicate key

---

Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/GraphViewerEditorWindow.cs

Graph viewer can now be opened with: `ctrl + g` or `cmd + g`!

Feature: added graph viewer shortcut

---

Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/NodeElement.cs

Feature: added target state indicator

---

Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Actions/EatAppleAction.cs
Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/AgentEditor.cs
Package/Runtime/CrashKonijn.Agent.Core/Interfaces/IAction.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/GoapActionBase.cs

Feature: added range information to agent editor

---

Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Builders/ActionBuilder.cs

Special thanks to Racines on Discord for the fix

Fix: ActionBuilder breaking from custom base classes

---

Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Runners/AgentTypeJobRunner.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentTypeJobRunnerTests.cs

Fix: resolver picking completed actions

---

Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/GoapActionProvider.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Runners/AgentTypeJobRunner.cs

Fix: Sensor runner breaking when switching agent types

---

Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Factories/CleanerAgentTypeConfigFactory.cs
Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IActionConfig.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/AgentTypeFactory.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Builders/ActionBuilder.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Builders/AgentTypeBuilder.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Builders/GoalBuilder.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Builders/MultiSensorBuilder.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Builders/TargetSensorBuilder.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Builders/WorldSensorBuilder.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Configs/ActionConfig.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Configs/GoalConfig.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Configs/MultiSensorConfig.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Configs/TargetSensorConfig.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Configs/WorldSensorConfig.cs

```csharp
capability.AddAction<HaulItemAction>()
.SetCallback((action) =>
{
Debug.Log($"Action callback: {action}");
});
```

Feature: added config callbacks

---

Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IKeyResolver.cs
Package/Runtime/CrashKonijn.Goap.Resolver/GraphBuilder.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Resolvers/KeyResolver.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Resolvers/KeyResolverBase.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/Data/TestKeyResolver.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/GraphBuilderTests.cs
Package/Tests/CrashKonijn.Goap.Tests/UnitTests/GraphBuilderTests.cs.meta

Fix: Prevent connecting actions with conflicting effects #314

---

Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/EditorWindowValues.cs
Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/GraphViewerEditorWindow.cs
Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/NodeElement.cs
Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/ToolbarElement.cs
Package/Editor/CrashKonijn.Goap.Editor/Styles/GraphViewer.uss

Allows you to toggle showing the config (target and effects) during play.
Fixes #316 
Fixes #315

Toggle show config during play

---

Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Actions/EatAction.cs
Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/SimpleHungerBehaviour.cs
Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/NodeElement.cs
Package/Runtime/CrashKonijn.Agent.Core/Interfaces/IAction.cs
Package/Runtime/CrashKonijn.Agent.Core/Interfaces/IActionProvider.cs
Package/Runtime/CrashKonijn.Agent.Runtime/ActionBase.cs
Package/Runtime/CrashKonijn.Agent.Runtime/ActionProviderBase.cs
Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IGoapAction.cs
Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/GoapActionBase.cs

The IActionDisabler was stored on the action itself, this was incorrect as this would count for all agents in a set.
Fixes #319

Fixes: Action disabler being implemented incorrectly

---

Package/Documentation/General/Generator.md
Package/Documentation/Introduction/Setup.md

Fix: docs unclear about generator namespace

---

Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Factories/CleanerAgentTypeConfigFactory.cs

Fix: Demo cleaner not cleaning last item

---

Package/Documentation/Examples/Complex.md

Fix: Minor docs mistake. Fixes #338
