crashkonijn/GOAP

- Demo/Assets/Demos/Complex/Behaviours/ComplexAgentBrain.cs
- Demo/Assets/Demos/Complex/Factories/Extensions/GoalExtensions.cs
- Package/package.json
Agents could get into a goal deadlock, the newly introduced `onGoalCompleted` event prevented the resolver from doing an action multiple twice, even if the goal was technically 'completed'.
I've fixed this in two ways:
- Added OnGoalCompleted event to `ComplexAgentBrain`, this will always prevent a deadlock.
- Increased the values used in the goals. This will prevent the goal being completed incorrectly.
> Fixed deadlock for agents in complex example

- Demo/Assets/Demos/Complex/Sensors/World/IsHoldingSensor.cs
- Demo/Assets/Demos/Simple/Sensors/World/HasAppleSensor.cs
- Demo/Assets/Demos/Simple/Sensors/World/IsHungrySensor.cs
- Package/Runtime/CrashKonijn.Goap/Classes/References/DataReferenceInjector.cs
- Package/Runtime/CrashKonijn.Goap/Interfaces/IComponentReference.cs
Method renaming:  GetComponent<T> becomes GetCachedComponent<T> to better communicate purpose.   For backward compatibility, previous versions retained but marked as obsolete.   Revised uses in the demo project also.
> Method renaming:  GetComponent<T> becomes GetCachedComponent<T>

- Demo/Assets/Demos/Complex/Behaviours/AgentSpawnBehaviour.cs
- Demo/Assets/Demos/Complex/Prefabs/ComplexAgent.prefab
- Demo/Assets/Demos/Complex/Scenes/ComplexDemoScene.unity
- Demo/Assets/Demos/Simple/Behaviours/SettingsBehaviour.cs
- Package/Editor/CrashKonijn.Goap.Editor/Drawers/GoapSetDrawer.cs
- Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/NodeViewerEditorWindow.cs
- Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/GoapRunnerEditor.cs
- Package/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs
- Package/Runtime/CrashKonijn.Goap/Behaviours/GoapRunnerBehaviour.cs
- Package/Runtime/CrashKonijn.Goap/Behaviours/GoapSetBehaviour.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Builders/GoapSetBuilder.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapRunner.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/ActionClassTypeValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/ActionConditionKeyValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/ActionEffectKeyValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/ActionEffectsValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/ActionTargetValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/Extensions.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/GoalClassTypeValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/GoalConditionKeyValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/GoalConditionsValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/GoapSetConfigValidatorRunner.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/TargetKeySensorsValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/TargetSensorClassTypeValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/TargetSensorKeyValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/WorldKeySensorsValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/WorldSensorClassTypeValidator.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Validators/WorldSensorKeyValidator.cs
- Package/Runtime/CrashKonijn.Goap/Interfaces/IGoapRunner.cs
- Package/Runtime/CrashKonijn.Goap/Interfaces/IGoapSetConfigValidatorRunner.cs
Major name refactor to change all derivatives of 'Set' to 'GoapSet'. This to mitigate possible confusion around the different meanings of the word 'set'. Backward compatibility has been preserved via the use of 'obsolete' on changed public properties and methods.
**WARNING!**
This change is 99% okay, apart from one issue.  The manual 'wiring up' of `GoapSetConfigFactories` within the `GoapRunnerBehaviour` component is problematic.
As you can see in this screenshot of the editor, I now have two arrays of AgentSetConfigFactories - `SetConfigFactories`, which I have labeled as obsolete, and `GoapSetConfigFactories`.  In the awake method of `GoapRunnerBehaviour`, I have made a check to see if the `goapSetConfigFactories` collection is empty, and if so, set it to equal the now obsolete …
> Major name refactor to change all derivatives of 'Set' to 'GoapSet'.

- Package/Runtime/CrashKonijn.Goap.Resolver/ConditionBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/ConditionBuilder.cs.meta
- Package/Runtime/CrashKonijn.Goap.Resolver/CostBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/ExecutableBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/GraphResolver.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/GraphResolverJob.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/Interfaces/IConditionBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/Interfaces/IConditionBuilder.cs.meta
- Package/Runtime/CrashKonijn.Goap.Resolver/Interfaces/ICostBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/Interfaces/IExecutableBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/Interfaces/IGraphResolver.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/Interfaces/IPositionBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/PositionBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Resolver/ResolveHandle.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapSetJobRunner.cs
- Package/Tests/CrashKonijn.Goap.Tests/UnitTests/GraphResolverTests.cs
- Fixes: Planner returning action for satisfied condition #36
Old situation:
```
foreach node
foreach node.connection
```
New situation:
```
foreach node
foreach node.condition
if node.condition is satisfied
continue;
foreach condition.connection
```
> Fixed planned planning action for satisfied condition

- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Actions/HaulItemAction.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapRunner.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapSetJobRunner.cs
- Fixed: Jobs not disposing correctly after exiting play
- Fixed: Complex example sometimes throwing null-ref, especially with large number of agents.
Fixes: #60
> Fixed: Jobs leaking when quitting play

- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Factories/Extensions/ActionExtensions.cs
- Package/Documentation/General/ConditionsAndEffects.md
- Package/Documentation/Introduction/Code.md
- Package/Editor/CrashKonijn.Goap.Editor/Drawers/SerializableEffectDrawer.cs
- Package/Editor/CrashKonijn.Goap.Editor/Drawers/SerializableEffectDrawer.cs.meta
- Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/NodeViewerEditorWindow.cs
- Package/Runtime/CrashKonijn.Goap/Behaviours/GoapRunnerBehaviour.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Builders/ActionBuilder.cs
- Package/Runtime/CrashKonijn.Goap/Enums/EffectType.cs
- Package/Runtime/CrashKonijn.Goap/Enums/EffectType.cs.meta
- Added possibility to add an `IGoapSetConfig` to the `GoapRunnerBehaviour`
- Added effect type (Increase/Decrease) instead of increase bool
- Added warning in the editor when no stylesheets could be loaded (project files have been moved to another location)
- Fixed: Node viewer not being draggable in 2021.x
> Various improvements

- Package/Runtime/CrashKonijn.Goap.Resolver/GraphResolverJob.cs
- Package/Tests/CrashKonijn.Goap.Tests/UnitTests/GraphResolverTests.cs
> Fixed resolver traversing action with unresolvable condition

- Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/NodeViewerEditorWindow.cs
* DebugGraph conflicts with non-namespaced Unity Packages like Squiggle
Fixes: #126
> DebugGraph conflict fix

- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Behaviours/AgentMoveBehaviour.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Shared/Behaviours/AgentMoveBehaviour.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/AgentMoveBehaviour.cs
- Package/Runtime/CrashKonijn.Goap.Core/Enums/AgentMoveState.cs
- Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IActionConfig.cs
- Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgentEvents.cs
- Package/Runtime/CrashKonijn.Goap/Behaviours/ActionBase.cs
- Package/Runtime/CrashKonijn.Goap/Behaviours/ActionRunner.cs
- Package/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs
- Package/Runtime/CrashKonijn.Goap/Behaviours/AgentEvents.cs
- Package/Runtime/CrashKonijn.Goap/Classes/Builders/ActionBuilder.cs
- Package/Runtime/CrashKonijn.Goap/Configs/ActionConfig.cs
- Package/Runtime/CrashKonijn.Goap/Scriptables/ActionConfigScriptable.cs
- Package/Runtime/CrashKonijn.Goap/Scriptables/CapabilityConfigScriptable.cs
- Package/Tests/CrashKonijn.Goap.Tests/UnitTests/ActionRunnerTests.cs
Fixes #165 
Changes:
- AgentEvents: renamed `OnTargetOutOfRange` to `TargetNotInRange` for clarity.
- ActionConfig: renamed `InRange` to `StoppingDistance` for clarity.
- AgentMoveState: renamed `OutOfRange` to `NotInRange` for clarity.
> Change: renamed in and out of range

- Package/Runtime/CrashKonijn.Agent.Core/Interfaces/IAgentEvents.cs
- Package/Runtime/CrashKonijn.Agent.Runtime/AgentBehaviour.cs
- Package/Runtime/CrashKonijn.Agent.Runtime/AgentEvents.cs
There is no way to know whether `AgentBehaviour`'s current target is missing using events. `TargetChanged` is not invoking in this case that's why I added this feature.
My use case: I have AgentMoveBehaviour to follow near enemies which are being detected using sensors. When the enemy goes out of the sensor radius, there is no way to prevent current movement using already implemented events.
> Feature: add TargetLost event

- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Goap/ItemTarget.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Sensors/Target/ClosestItemSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Sensors/Target/ClosestObjectSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Sensors/Target/ClosestSourceSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Sensors/Target/HaulTargetSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Sensors/Target/TransformSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Sensors/Target/WanderTargetSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Shared/Sensors/Target/TransformSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Shared/Sensors/Target/WanderTargetSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Sensors/Multi/AppleSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Sensors/Target/AgentSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Sensors/Target/ClosestTreeSensor.cs
- Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Sensors/Target/WanderTargetSensor.cs
- Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IMultiSensor.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Classes/PositionTarget.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Classes/TransformTarget.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Sensors/GlobalTargetSensorBase.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Sensors/LocalTargetSensorBase.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Sensors/MultiSensorBase.cs
- Package/Tests/CrashKonijn.Goap.Tests/UnitTests/Data/LocalTargetSensor.cs
- Package/Tests/CrashKonijn.Goap.Tests/UnitTests/MultiSensorBaseTests.cs
Provides the previous target in target sensors. The existing ITarget implementations have been updated so their value can be updated.
```csharp
public override ITarget Sense(IActionReceiver agent, IComponentReference references, ITarget target)
{
// It's always the same target, return it again if it already exists
if (target != null)
return target;
return new TransformTarget(agent.Transform);
}
```
> Feature: provide previous target in sensor

- Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Runners/SensorRunner.cs
> Fix: Unityeditor refference in class

- Package/Documentation/General/Controllers.md
- Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Runners/AgentTypeJobRunner.cs
- Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentTypeJobRunnerTests.cs
The resolver now checks if the MayResolve method on the currently active IActionRunState returns true. This allows you to disable the resolver during an action.
> Feature: Implemented IActionRunstate.MayResolve logic

- Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Capabilities/TestCapability.asset
- Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Capabilities/TestCapability.asset.meta
- Package/Editor/CrashKonijn.Goap.Editor/Elements/ListElementBase.cs
- Package/Editor/CrashKonijn.Goap.Editor/Elements/SensorList.cs
> Fix: Fixes various SO config errors

- Package/Documentation/Introduction/Pears.md
This pull request includes an enhancement to the `Package/Documentation/Introduction/Pears.md` file. The most important change is the addition of a new sensor to the builder configuration.
Enhancement to documentation:
* [`Package/Documentation/Introduction/Pears.md`](diffhunk://#diff-4748690271c80e7082da127dad969b4db66646b5ad1468c41f1a096d98bd9ae5R228-R229): Added `PearSensor` to the builder with the `AddMultiSensor` method.
> Fix: Missing reference in tutorial

- Package/Documentation/Introduction/Setup.md
Following this guide using scripts method, the string used to for GetAgentType is incorrect and should be "ScriptDemoAgent"
> Corrects agent type string

- Package/Editor/CrashKonijn.Goap.Editor/Drawers/ObjectDrawer.cs
- Package/Editor/CrashKonijn.Goap.Editor/Drawers/WorldDataDrawer.cs
- Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/ConnectionElement.cs
- Package/Editor/CrashKonijn.Goap.Editor/GraphViewer/NodeElement.cs
- Package/Runtime/CrashKonijn.Agent.Core/Extensions.cs
- Package/Runtime/CrashKonijn.Agent.Core/Extensions.cs.meta
- Package/Runtime/CrashKonijn.Agent.Runtime/VectorDistanceObserver.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Runners/AgentTypeJobRunner.cs
This pull request includes several changes aimed at improving the handling of target positions and ensuring validity checks across the codebase. The most important changes include adding a new extension method for validating target positions, updating various methods to use this new validation method, and adding additional null checks.
* [`Package/Runtime/CrashKonijn.Agent.Core/Extensions.cs`](diffhunk://#diff-21c116f02447c1b8513e781ccde4a9804b7a2c8d168e11cdb78ac9fd53502b0dR1-R18): Added a new extension method `GetValidPosition` to validate target positions.
* [`Package/Editor/CrashKonijn.Goap.Editor/Drawers/ObjectDrawer.cs`](diffhunk://#diff-b78d9b3250661dc14500ba5d2fac4c70021d109472f76b7677671d3cb7d4524cL51-R52): Updated `GetValueString` method to use `GetValidPosition` for …
> Fix: Invalid target's position being used

- Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgentType.cs
- Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IGoapActionProvider.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/GoapActionProvider.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Classes/AgentType.cs
- Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentBehaviourTests.cs
The current `GoapActionProvider` implementation has two limitations:
1. It only supports requesting goals via generic type parameters, which limits the number of goals that can be requested
2. It doesn't support dynamic goal requests from external configuration files (CSV/JSON/XML)
Added support for requesting goals by passing Type objects directly. This enables:
- Dynamic goal creation from configuration files
- No limit on the number of goals that can be requested simultaneously
```csharp
// Before - Limited to generic parameters
_provider.RequestGoal<IdleGoal>();
// After - Supports dynamic goal requests
RequestGoal("IdleGoal");
private void RequestGoal(params string[] goals)
{
var assembly = Assembly.GetExecutingAssembly();
var types = goals.Select(goal => …
```
> Enhanced Goal Request Flexibility in GoapActionProvider

- Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/AgentTypeBehaviour.cs
**Is your feature request related to a problem? Please describe.**
In order to inherit from AgentTypeBehaviour, I need to be able to set the `AgentTypeScriptable config` and `GoapBehaviour runner` and override the Awake logic if neccessary.
> Enhancement: Allow AgentTypeBehaviour to be more easily subclassed

- Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/GoapActionBase.cs
Added a virtual method to override IsInRange in GoapActionBase, similar to how IsValid and other methods in that class work so the method signature with the generic parameters can be overridden and still have the type safety from the generics
> Enhancement: GoapActionBehaviour IsInRange overriding

- Package/Editor/CrashKonijn.Goap.Editor/Elements/ActionPropertiesElement.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Builders/ActionBuilder.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Extensions.cs
`ActionPropertiesElement` doesnt support displaying Action Properties if the Actions don't directly inherit from `GoapActionBase<,>` 
In my usecase, I have a subclass of GoapActionBase to perform my own abstractions
For example:
```cs
public class MyAction : MyActionBase<MyAction.Data, MyAction.Props>
{
public override IActionRunState Perform(IMonoAgent agent, Data data, IActionContext context) => throw new System.NotImplementedException();
public class Props : IActionProperties
{
public bool MyBool;
}
public class Data : SharedData
{
public int MyInt;
}
}
public class SharedData : IActionData
{
public ITarget Target { get; set; }
public string someSharedData;
}
public abstract class MyActionBase<TActionData> : MyActionBase<TActionData, EmptyActionProperties>
where TActionData : …
```
> Fix GoapActionBase subclasses not rendering ActionProperties in Capabilities

- Package/Documentation/Classes/Actions.md
- Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IGoapActionProvider.cs
- Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/GoapActionProvider.cs
> Feature: Easier enable/disable of actions
